version: '3'


services: 
    mongodb:
        image: mongo:4.4
        container_name: mongo-service
        restart: always
        ports: 
            - "27017:27017"
        volumes: 
            - ./data:/data/db